spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
#    bus:
#     trace:
#      enabled:true
  profiles:
     active: native
  rabbitmq:
    host: 192.168.20.132
    port: 5672
    username: root
    password: root
server:
  port: 8888
management:
  endpoints:
    web:
      cors:
        allow-credentials: true
        allowed-headers: '*'
        allowed-methods: '*'
        allowed-origins: '*'
        exposed-headers: 'header1,header2'
        max-age: 1800s
#security:
#  user:
#    password: root