server:
  port: 8761
spring:
  profiles: slave1
  rabbitmq:
   host: 10.11.85.21
   port: 5672
   username: root
   password: 123456
  
eureka:
  client:
    instance:
     hostname: slave1
    serviceUrl:
      defaultZone: http://slave2:8762/eureka/
---
server:
  port: 8762
spring:
  profiles: slave2
  rabbitmq:
   host: 10.11.85.21
   port: 5672
   username: root
   password: 123456
eureka:
  instance:
    hostname: slave2
  client:
    serviceUrl:
      defaultZone: http://slave1:8761/eureka/