server:
  port: 8001
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:                           # 指定数据源
#   type: com.alibaba.druid.pool.DruidDataSource		#spring boot1.4不支持type，使用自定义DataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ticket?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: root
    initialSize: 50
    minIdle: 5
    maxActive: 20	
    maxWait: 60000	
    filters: stat
    minEvictableIdleTimeMillis: 300000		# 配置一个连接在池中最小生存的时间，单位是毫秒
    poolPreparedStatements: true
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch.youran.persistence: ERROR
eureka:
  instance:
    preferIpAddress: true