server:
  port: 8761
spring:
  profiles: slave1
  
eureka:
  client:
    instance:
     hostname: slave1
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://slave2:8762/eureka/
---
server:
  port: 8762
spring:
  profiles: slave2
eureka:
  instance:
    hostname: slave2
  client:
    serviceUrl:
      defaultZone: http://slave1:8761/eureka/